.PHONY: clean All

All:
	@echo "----------Building project:[ Realtional_Operators - Debug ]----------"
	@cd "Realtional_Operators" && "$(MAKE)" -f  "Realtional_Operators.mk"
clean:
	@echo "----------Cleaning project:[ Realtional_Operators - Debug ]----------"
	@cd "Realtional_Operators" && "$(MAKE)" -f  "Realtional_Operators.mk" clean
