.PHONY: clean All

All:
	@echo "----------Building project:[ Logical_Operators - Debug ]----------"
	@cd "Logical_Operators" && "$(MAKE)" -f  "Logical_Operators.mk"
clean:
	@echo "----------Cleaning project:[ Logical_Operators - Debug ]----------"
	@cd "Logical_Operators" && "$(MAKE)" -f  "Logical_Operators.mk" clean
