.PHONY: clean All

All:
	@echo "----------Building project:[ switch-case_statement - Debug ]----------"
	@cd "switch-case_statement" && "$(MAKE)" -f  "switch-case_statement.mk"
clean:
	@echo "----------Cleaning project:[ switch-case_statement - Debug ]----------"
	@cd "switch-case_statement" && "$(MAKE)" -f  "switch-case_statement.mk" clean
