.PHONY: clean All

All:
	@echo "----------Building project:[ Increment_and_Decrement_Operators - Debug ]----------"
	@cd "Increment_and_Decrement_Operators" && "$(MAKE)" -f  "Increment_and_Decrement_Operators.mk"
clean:
	@echo "----------Cleaning project:[ Increment_and_Decrement_Operators - Debug ]----------"
	@cd "Increment_and_Decrement_Operators" && "$(MAKE)" -f  "Increment_and_Decrement_Operators.mk" clean
