.PHONY: clean All

All:
	@echo "----------Building project:[ Conditional_Operator - Debug ]----------"
	@cd "Conditional_Operator" && "$(MAKE)" -f  "Conditional_Operator.mk"
clean:
	@echo "----------Cleaning project:[ Conditional_Operator - Debug ]----------"
	@cd "Conditional_Operator" && "$(MAKE)" -f  "Conditional_Operator.mk" clean
