.PHONY: clean All

All:
	@echo "----------Building project:[ Declaring_and_Using_Constants - Debug ]----------"
	@cd "Declaring_and_Using_Constants" && "$(MAKE)" -f  "Declaring_and_Using_Constants.mk"
clean:
	@echo "----------Cleaning project:[ Declaring_and_Using_Constants - Debug ]----------"
	@cd "Declaring_and_Using_Constants" && "$(MAKE)" -f  "Declaring_and_Using_Constants.mk" clean
