.PHONY: clean All

All:
	@echo "----------Building project:[ Accesing_and_Modifying_Array_Elements - Debug ]----------"
	@cd "Accesing_and_Modifying_Array_Elements" && "$(MAKE)" -f  "Accesing_and_Modifying_Array_Elements.mk"
clean:
	@echo "----------Cleaning project:[ Accesing_and_Modifying_Array_Elements - Debug ]----------"
	@cd "Accesing_and_Modifying_Array_Elements" && "$(MAKE)" -f  "Accesing_and_Modifying_Array_Elements.mk" clean
