.PHONY: clean All

All:
	@echo "----------Building project:[ Firstproject - Debug ]----------"
	@cd "Firstproject" && "$(MAKE)" -f  "Firstproject.mk"
clean:
	@echo "----------Cleaning project:[ Firstproject - Debug ]----------"
	@cd "Firstproject" && "$(MAKE)" -f  "Firstproject.mk" clean
