.PHONY: clean All

All:
	@echo "----------Building project:[ Size_of_Variable__sizeof - Debug ]----------"
	@cd "Size_of_Variable__sizeof" && "$(MAKE)" -f  "Size_of_Variable__sizeof.mk"
clean:
	@echo "----------Cleaning project:[ Size_of_Variable__sizeof - Debug ]----------"
	@cd "Size_of_Variable__sizeof" && "$(MAKE)" -f  "Size_of_Variable__sizeof.mk" clean
