.PHONY: clean All

All:
	@echo "----------Building project:[ Course_first_challenge - Debug ]----------"
	@cd "Course_first_challenge" && "$(MAKE)" -f  "Course_first_challenge.mk"
clean:
	@echo "----------Cleaning project:[ Course_first_challenge - Debug ]----------"
	@cd "Course_first_challenge" && "$(MAKE)" -f  "Course_first_challenge.mk" clean
