.PHONY: clean All

All:
	@echo "----------Building project:[ Testing_for_Equality - Debug ]----------"
	@cd "Testing_for_Equality" && "$(MAKE)" -f  "Testing_for_Equality.mk"
clean:
	@echo "----------Cleaning project:[ Testing_for_Equality - Debug ]----------"
	@cd "Testing_for_Equality" && "$(MAKE)" -f  "Testing_for_Equality.mk" clean
