.PHONY: clean All

All:
	@echo "----------Building project:[ Vjezba5 - Debug ]----------"
	@cd "Vjezba5" && "$(MAKE)" -f  "Vjezba5.mk"
clean:
	@echo "----------Cleaning project:[ Vjezba5 - Debug ]----------"
	@cd "Vjezba5" && "$(MAKE)" -f  "Vjezba5.mk" clean
