.PHONY: clean All

All:
	@echo "----------Building project:[ Declaring_and_Initializing_Variables - Debug ]----------"
	@cd "Declaring_and_Initializing_Variables" && "$(MAKE)" -f  "Declaring_and_Initializing_Variables.mk"
clean:
	@echo "----------Cleaning project:[ Declaring_and_Initializing_Variables - Debug ]----------"
	@cd "Declaring_and_Initializing_Variables" && "$(MAKE)" -f  "Declaring_and_Initializing_Variables.mk" clean
