.PHONY: clean All

All:
	@echo "----------Building project:[ Variables_and_Constants_Challenge - Debug ]----------"
	@cd "Variables_and_Constants_Challenge" && "$(MAKE)" -f  "Variables_and_Constants_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Variables_and_Constants_Challenge - Debug ]----------"
	@cd "Variables_and_Constants_Challenge" && "$(MAKE)" -f  "Variables_and_Constants_Challenge.mk" clean
