.PHONY: clean All

All:
	@echo "----------Building project:[ Vector_Challenge - Debug ]----------"
	@cd "Vector_Challenge" && "$(MAKE)" -f  "Vector_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Vector_Challenge - Debug ]----------"
	@cd "Vector_Challenge" && "$(MAKE)" -f  "Vector_Challenge.mk" clean
