.PHONY: clean All

All:
	@echo "----------Building project:[ IF_Else_Statements - Debug ]----------"
	@cd "IF_Else_Statements" && "$(MAKE)" -f  "IF_Else_Statements.mk"
clean:
	@echo "----------Cleaning project:[ IF_Else_Statements - Debug ]----------"
	@cd "IF_Else_Statements" && "$(MAKE)" -f  "IF_Else_Statements.mk" clean
