.PHONY: clean All

All:
	@echo "----------Building project:[ Statement_and_Operator_Challenge_ - Debug ]----------"
	@cd "Statement_and_Operator_Challenge_" && "$(MAKE)" -f  "Statement_and_Operator_Challenge_.mk"
clean:
	@echo "----------Cleaning project:[ Statement_and_Operator_Challenge_ - Debug ]----------"
	@cd "Statement_and_Operator_Challenge_" && "$(MAKE)" -f  "Statement_and_Operator_Challenge_.mk" clean
