.PHONY: clean All

All:
	@echo "----------Building project:[ cout_test - Debug ]----------"
	@cd "cout_test" && "$(MAKE)" -f  "cout_test.mk"
clean:
	@echo "----------Cleaning project:[ cout_test - Debug ]----------"
	@cd "cout_test" && "$(MAKE)" -f  "cout_test.mk" clean
