.PHONY: clean All

All:
	@echo "----------Building project:[ IF_Statement - Debug ]----------"
	@cd "IF_Statement" && "$(MAKE)" -f  "IF_Statement.mk"
clean:
	@echo "----------Cleaning project:[ IF_Statement - Debug ]----------"
	@cd "IF_Statement" && "$(MAKE)" -f  "IF_Statement.mk" clean
