.PHONY: clean All

All:
	@echo "----------Building project:[ C_Built-in_Primitive_Types - Debug ]----------"
	@cd "C_Built-in_Primitive_Types" && "$(MAKE)" -f  "C_Built-in_Primitive_Types.mk"
clean:
	@echo "----------Cleaning project:[ C_Built-in_Primitive_Types - Debug ]----------"
	@cd "C_Built-in_Primitive_Types" && "$(MAKE)" -f  "C_Built-in_Primitive_Types.mk" clean
