.PHONY: clean All

All:
	@echo "----------Building project:[ Mixed_Expressions_and_Conversion - Debug ]----------"
	@cd "Mixed_Expressions_and_Conversion" && "$(MAKE)" -f  "Mixed_Expressions_and_Conversion.mk"
clean:
	@echo "----------Cleaning project:[ Mixed_Expressions_and_Conversion - Debug ]----------"
	@cd "Mixed_Expressions_and_Conversion" && "$(MAKE)" -f  "Mixed_Expressions_and_Conversion.mk" clean
