.PHONY: clean All

All:
	@echo "----------Building project:[ Global_Variables - Debug ]----------"
	@cd "Global_Variables" && "$(MAKE)" -f  "Global_Variables.mk"
clean:
	@echo "----------Cleaning project:[ Global_Variables - Debug ]----------"
	@cd "Global_Variables" && "$(MAKE)" -f  "Global_Variables.mk" clean
