.PHONY: clean All

All:
	@echo "----------Building project:[ The_Assigment_Operator - Debug ]----------"
	@cd "The_Assigment_Operator" && "$(MAKE)" -f  "The_Assigment_Operator.mk"
clean:
	@echo "----------Cleaning project:[ The_Assigment_Operator - Debug ]----------"
	@cd "The_Assigment_Operator" && "$(MAKE)" -f  "The_Assigment_Operator.mk" clean
